=== antoinebarbier022/cv-generator-tauri/src-tauri/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "general": {
      "type": "object",
      "properties": {
        "firstname": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        },
        "role": {
          "type": "string"
        },
        "grade": {
          "type": "string",
          "enum": ["A", "B", "C", "D", "E", "F"]
        },
        "entity": {
          "type": "string"
        },
        "team": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "linkedin": {
          "type": "string"
        },
        "twitter": {
          "type": "string"
        }
      },
      "required": [
        "firstname",
        "lastname",
        "role",
        "grade",
        "entity",
        "team",
        "description",
        "linkedin",
        "twitter"
      ]
    },
    "formations": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "employment_history": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "articles_and_others": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "sectors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "skills": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "languages": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "experiences": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "program": {
            "type": "string"
          },
          "client": {
            "type": "string"
          },
          "role": {
            "type": "string"
          },
          "date": {
            "type": "string"
          },
          "context": {
            "type": "string"
          },
          "contribution": {
            "type": "string"
          }
        },
        "required": [
          "program",
          "client",
          "role",
          "date",
          "context",
          "contribution"
        ]
      }
    }
  },
  "required": [
    "general",
    "formations",
    "employment_history",
    "articles_and_others",
    "sectors",
    "skills",
    "languages",
    "experiences"
  ]
}

=== antoinebarbier022/cv-generator-tauri/src-tauri/resources/data_en.json
{
  "$schema": "./schema.json",
  "general": {
    "firstname": "Antoine",
    "lastname": "Barbier",
    "role": "Frontend Developer",
    "grade": "A",
    "entity": "ISD",
    "team": "INNOVATION STRATEGY & DESIGN",
    "description": "Frontend web developer specialized in JS development and Design System implementation. Strong interest in design.\nGraduated in 2022 with a Master's degree in Software Engineering from the Faculty of Sciences in Montpellier.",
    "linkedin": "antoinebarbier022",
    "twitter": "-"
  },
  "formations": [
    "Master's in Software Engineering (2020 - 2022)",
    "Bachelor's in Computer Science (2017 - 2020)",
    "Baccalaureate in Life Sciences and Computer Science (2017)"
  ],
  "employment_history": ["Deliveroo"],
  "articles_and_others": [],
  "sectors": [],
  "skills": [
    "Javascript/Typescript",
    "React, VueJs, Lit, Angular",
    "Storybook",
    "HTML, CSS / SCSS / Tailwind",
    "Apollo (GraphQL)",
    "Figma"
  ],
  "languages": ["French – Fluent", "English – B1"],
  "experiences": [
    {
      "program": "MS Study Copilot",
      "client": "Microsoft",
      "role": "Developer",
      "date": "(06/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "Prompt Academy JS",
      "client": "Capgemini Invent",
      "role": "Developer",
      "date": "(05/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "GenAI MVP MRSIE",
      "client": "Ministère de l'intérieur",
      "role": "Developer",
      "date": "(04/24 - 09/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "Mesure Affluence",
      "client": "RATP",
      "role": "Developer",
      "date": "(04/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "GenAI FragWizard POC Mobile",
      "client": "Channel",
      "role": "Developer",
      "date": "(03/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "POC GenAI Chatbot",
      "client": "Stellantis",
      "role": "Developer",
      "date": "(02/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "POC RAG KO CAP",
      "client": "Capgemini",
      "role": "Developer",
      "date": "(01/24 - 02/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "POC GenAI SI Europe",
      "client": "Ministère de l'intérieur",
      "role": "Developer",
      "date": "(01/24 - 02/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "POC MESDMP",
      "client": "AVV frog",
      "role": "Developer",
      "date": "(12/23)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "GenAI FragGPT",
      "client": "Channel",
      "role": "Developer",
      "date": "(11/23)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "POC GenAI",
      "client": "SANOFI",
      "role": "Developer",
      "date": "(09/23 – 10/23)",
      "context": "",
      "contribution": "Set up a frontend web application for a client demonstration. Tools: React, MUI JOY, React Query, i18n"
    },
    {
      "program": "NOMINEO",
      "client": "Generali",
      "role": "Creative Technologist",
      "date": "(08/23 – 09/23)",
      "context": "",
      "contribution": "Assisted the client in setting up Storybook and the component library + developed initial components. Tools: Angular, Angular Material, Storybook"
    },
    {
      "program": "Asgard",
      "client": "Internal",
      "role": "Project Manager and Frontend Developer",
      "date": "(06/23 – Present)",
      "context": "",
      "contribution": "Web application for technical monitoring at frog. Established a team and SCRUM methodology, frontend development, design of mockups. Tools: Jira, Figma. Tech: React, Storybook"
    },
    {
      "program": "Mobility4you",
      "client": "BNP Paribas",
      "role": "Developer",
      "date": "(11/22 – 06/23)",
      "context": "Website for vehicle rentals and purchases.",
      "contribution": "Developed pages and web components for an external integrator. Tech: Lit (web components), Storybook"
    },
    {
      "program": "GARNIER",
      "client": "L’OREAL",
      "role": "Developer",
      "date": "(06/22 – 07/22)",
      "context": "Showcase website template for Garnier brand products.",
      "contribution": "Frontend contribution and bug resolution. Tech: VueJS, Tailwind"
    },
    {
      "program": "POC: Design Tokens Automation",
      "client": "Internal frog",
      "role": "Developer",
      "date": "(05/23)",
      "context": "Automatic conversion of design tokens from Figma to a GitHub repository.",
      "contribution": "Development of the POC, automatic changelog, package. Tools: Style Dictionary, GitHub"
    },
    {
      "program": "CRAconverter",
      "client": "Internal frog",
      "role": "Developer",
      "date": "(11/22)",
      "context": "Website to format CSV files",
      "contribution": "Understanding the requirement and proposing a solution, development of a tool in 1 week, testing, design. Tech: REACT, ElectronJs, Storybook"
    },
    {
      "program": "Popcorn",
      "client": "Internal frog",
      "role": "Developer",
      "date": "(10/22 – 11/22)",
      "context": "Contribution to the Popcorn time tracking application",
      "contribution": "Refactoring, front-end architecture correction, implementation of a storybook, bug fixes. Tech: React, Storybook"
    },
    {
      "program": "Loki",
      "client": "Internal frog",
      "role": "Developer",
      "date": "(01/22 - 06/22)",
      "context": "Application to reference the skills and preferences of frog employees.",
      "contribution": "Implementation of tech tools, design, front-end development, testing, documentation. Tech: React, Apollo (GraphQL), Tailwind, Storybook"
    }
  ]
}

=== antoinebarbier022/cv-generator-tauri/src-tauri/resources/data_fr.json
{
  "$schema": "./schema.json",
  "general": {
    "firstname": "Antoine",
    "lastname": "Barbier",
    "role": "Développeur Frontend",
    "grade": "A",
    "entity": "ISD",
    "team": "INNOVATION STRATEGY & DESIGN",
    "description": "Développeur web frontend spécialisé dans le développement JS et en implémentation de Design System. Possède une forte appétence pour le design.\nDiplômé en 2022 d’un Master 2 en Génie Logiciel à la faculté des sciences de Montpellier.",
    "linkedin": "antoinebarbier022",
    "twitter": "-"
  },
  "formations": [
    "Master en Génie Logiciel (2020 - 2022)",
    "Licence Informatique (2017 - 2020)",
    "Baccalauréat spé SVT Option Informatique (2017)"
  ],
  "employment_history": ["Deliveroo"],
  "articles_and_others": [],
  "sectors": [
    "Développement Web Front-End",
    "Design System",
    "Documentation Storybook"
  ],
  "skills": [
    "Javascript/Typescript",
    "React, VueJs, Lit, Angular",
    "Storybook",
    "HTML, CSS / SCSS / Tailwind",
    "Apollo (GraphQL)",
    "Figma"
  ],
  "languages": ["Français – Courant", "Anglais – B1"],
  "experiences": [
    {
      "program": "MS Study Copilot",
      "client": "Microsoft",
      "role": "Développeur",
      "date": "(06/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "Prompt Academy JS",
      "client": "Capgemini Invent",
      "role": "Développeur",
      "date": "(05/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "GenAI MVP MRSIE",
      "client": "Ministère de l'intérieur",
      "role": "Développeur",
      "date": "(04/24 - 09/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "Mesure Affluence",
      "client": "RATP",
      "role": "Développeur",
      "date": "(04/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "GenAI FragWizard POC Mobile",
      "client": "Channel",
      "role": "Développeur",
      "date": "(03/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "POC GenAI Chatbot",
      "client": "Stellantis",
      "role": "Développeur",
      "date": "(02/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "POC RAG KO CAP",
      "client": "Capgemini",
      "role": "Développeur",
      "date": "(01/24 - 02/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "POC GenAI SI Europe",
      "client": "Ministère de l'intérieur",
      "role": "Développeur",
      "date": "(01/24 - 02/24)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "POC MESDMP",
      "client": "AVV frog",
      "role": "Développeur",
      "date": "(12/23)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "GenAI FragGPT",
      "client": "Channel",
      "role": "Développeur",
      "date": "(11/23)",
      "context": "",
      "contribution": ""
    },
    {
      "program": "POC GenAI",
      "client": "SANOFI",
      "role": "Développeur",
      "date": "(09/23 – 10/23)",
      "context": "",
      "contribution": "Mise en place d’une application web frontend pour une démonstration client. Outils: React, MUI JOY, React Query, i18n"
    },
    {
      "program": "NOMINEO",
      "client": "Generali",
      "role": "Creative Technologist",
      "date": "(08/23 – 09/23)",
      "context": "",
      "contribution": "Accompagnement du client dans la mise en place du Storybook et de la « library » + développement des premiers composants. Outils: Angular, Angular Material, Storybook"
    },
    {
      "program": "Asgard",
      "client": "Interne",
      "role": "Chef de projet et dev front",
      "date": "(06/23 – Aujourd’hui)",
      "context": "",
      "contribution": "Application web pour le suivi de la veille technique chez frog. Mise en place d’une équipe et méthodologie SCRUM, développement du front, design des maquettes. Outils : Jira, Figma. Tech : React, Storybook"
    },
    {
      "program": "Mobility4you",
      "client": "BNP Paribas",
      "role": "Développeur",
      "date": "(11/22 – 06/23)",
      "context": "Site web de locations et achats de véhicules.",
      "contribution": "Développement de pages et de web components à destination d’un intégrateur externe. Tech : Lit (web components), Storybook"
    },
    {
      "program": "GARNIER",
      "client": "L’OREAL",
      "role": "Développeur",
      "date": "(06/22 – 07/22)",
      "context": "Site vitrine sous forme de template pour des produits de la marque Garnier.",
      "contribution": "Contribution front et résolution de bugs. Tech : VueJS, Tailwind"
    },
    {
      "program": "POC : Design Tokens automatisation",
      "client": "Interne frog",
      "role": "Développeur",
      "date": "(05/23)",
      "context": "Conversion automatique des design tokens depuis Figma vers un répertoire GitHub.",
      "contribution": "Développement du POC, changelog automatique, package. Outils : Style Dictionary, Github"
    },
    {
      "program": "CRAconverter",
      "client": "Interne frog",
      "role": "Développeur",
      "date": "(11/22)",
      "context": "Site web pour formater des fichiers CSV",
      "contribution": "Compréhension du besoin et proposition d’une solution, développement d’un outil en 1 semaine, tests, design. Tech : REACT, ElectronJs, Storybook"
    },
    {
      "program": "Popcorn",
      "client": "Interne frog",
      "role": "Développeur",
      "date": "(10/22 – 11/22)",
      "context": "Contribution à l’application d’imputation Popcorn",
      "contribution": "Refactoring, correction de l’architecture front, mise en place d’un storybook, corrections de Bugs. Tech : React, Storybook"
    },
    {
      "program": "Loki",
      "client": "Interne frog",
      "role": "Développeur",
      "date": "(01/22 - 06/22)",
      "context": "Application pour référencer les compétences et appétences des collaborateurs de frog.",
      "contribution": "Mise en place d’outils tech, design, développement front, tests, documentation. Tech : React, Apollo (GraphQL),Tailwind, Storybook"
    }
  ]
}
